### ISSUE TITLE
Receiving an exception after selecting basic fields

### ISSUE THREAD

**Issue by wellhausen** [activeprospect/generator-leadconduit-integration#1]
Here are the steps for recreating the error: 
1. create a public repo: ros3bud/leadconduit-integration-requestBin1
2. create and cd into directory: Documents/leadconduit-integration-requestBin1
3. run yo leadconduit-integration
4. hit enter for name of service '(RequestBin1)'
5. select integration type: 'Outbound'
6. add service's URL: 'http://requestb.in/130wl15'
7. hit enter for HTTP method 'POST'
8. hit enter for 'No or not sure' for does the service require authentication?
9. hit enter for 'Standard Form POST' for what format is the service expecting?
10. arrow down to select 'XML (text/xml)' for what format does the service respond with?
11. hit space bar for 'First Name', 'Last Name', 'Email' 
12. hit enter

After hitting enter, the following error is visible in my terminal: 

/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8913
                throw e;
                      ^
TypeError: Cannot read property '1' of null
    at yeoman.generators.Base.extend._processAnswers (/usr/local/lib/node_modules/generator-leadconduit-integration/app/index.js:275:30)
    at PromptUI.completed (/usr/local/lib/node_modules/generator-leadconduit-integration/app/index.js:215:14)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1761:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:1698:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8933:31)
    at%

Here is an image of my terminal window with the error: 
![screenshot 2014-10-27 10 47 07](https://cloud.githubusercontent.com/assets/3402403/4793799/919d9f5c-5df0-11e4-931d-d75826ad3199.png)

**Comment by cgrayson** [comment]
This should be fixed. @ros3bud, if you would update your local generator (`npm update -g generator-leadconduit-integration` should do it) and try again?

**Comment by wellhausen** [comment]
This is fixed. Thanks!
