### ISSUE TITLE
Cake test throws error: Cannot find module 'leadconduit-fields'

### ISSUE THREAD

**Issue by wellhausen** [activeprospect/generator-leadconduit-integration#3]
Here are the steps to duplicate the issue: 
1. npm update -g generator-leadcoduit-integration
2. cd leadconduit-integration-requestBin
3. Answer all prompt questions 
4. run cake test from documents/leadconduit-integration-requestBin

module.js:340
    throw err;
          ^
Error: Cannot find module 'leadconduit-fields'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/ap/Documents/leadconduit-integration-requestBin/spec/outbound-spec.coffee:2:10)
  at Object.<anonymous> (/Users/ap/Documents/leadconduit-integration-requestBin/spec/outbound-spec.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/ap/Documents/leadconduit-integration-requestBin/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/ap/Documents/leadconduit-integration-requestBin/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /Users/ap/Documents/leadconduit-integration-requestBin/node_modules/mocha/lib/mocha.js:184:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/ap/Documents/leadconduit-integration-requestBin/node_modules/mocha/lib/mocha.js:181:14)
  at Mocha.run (/Users/ap/Documents/leadconduit-integration-requestBin/node_modules/mocha/lib/mocha.js:393:31)
  at Object.<anonymous> (/Users/ap/Documents/leadconduit-integration-requestBin/node_modules/mocha/bin/_mocha:380:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by wellhausen** [comment]
Here is the repo for reference: https://github.com/ros3bud/leadconduit-integration-requestBin

**Comment by cgrayson** [comment]
TIL: putting "fixes #x" in the commit message auto-closes the issue. Neat. 

This is ready for another `npm update` and try again whenever you have a chance, @ros3bud. Thanks.
